name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Vulkan SDK 1.3.296.0
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe" -OutFile "vulkan-sdk-installer.exe"
          Start-Process -Wait -FilePath "vulkan-sdk-installer.exe" -ArgumentList "/S", "/D=C:\VulkanSDK"

      - name: Set Vulkan SDK Path
        run: echo "VULKAN_SDK=C:\\VulkanSDK\\1.3.296.0" >> $env:GITHUB_ENV

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release
