name: Build Vulkan Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clean up previous build
        run: |
            Remove-Item -Recurse -Force "${{ github.workspace }}/build"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # This initializes and updates submodules
      - name: Set up Vulkan SDK
        uses: humbletim/install-vulkan-sdk@c2aa128094d42ba02959a660f03e0a4e012192f9
        with:
          version: 1.3.296.0
          cache: true

      - name: Set environment variable for Vulkan SDK
        run: |
          echo "VULKAN_SDK=C:/vulkan-sdk" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV

      - name: Build project (Release)
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DVULKAN_SDK=$VULKAN_SDK ..
          cmake --build . --config Release

      - name: Build project (Debug)
        run: |
          mkdir build-debug
          cd build-debug
          cmake -G "Visual Studio 17 2022" -DVULKAN_SDK=$VULKAN_SDK -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --config Debug
