name: Build Vulkan Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vulkan SDK
        uses: NcStudios/VulkanCI@v1.0
        with:
          sdkVersion: 1.3.296.0
          installPath: 'C:/vulkan-sdk'

      - name: Set environment variable for Vulkan SDK
        run: |
          echo "VULKAN_SDK=C:/vulkan-sdk" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DVULKAN_SDK=$VULKAN_SDK ..
          cmake --build . --config Release
