name: Build Vulkan Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vulkan SDK
        uses: humbletim/install-vulkan-sdk@c2aa128094d42ba02959a660f03e0a4e012192f9
        with:
          version: 1.3.296.0
          cache: true

      - name: Set environment variable for Vulkan SDK
        run: |
          echo "VULKAN_SDK=C:/vulkan-sdk" >> $GITHUB_ENV
          echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV

      # - name: Cache Vulkan SDK
      #   uses: actions/cache@v2
      #   with:
      #     path: C:/vulkan-sdk
      #     key: ${{ runner.os }}-vulkan-sdk-${{ hashFiles('**/*.cpp') }}

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DVULKAN_SDK=$VULKAN_SDK ..
          cmake --build . --config Release